### ISSUE TITLE
a breadcrumb module that supports tokens

### ISSUE THREAD

**Issue by simesy** [frees-au/ce#63]
I don't like drupal's default breadcrumb handling. I want breadcrumbs based on tokens.

**Comment by tannguyen04** [comment]
The https://www.drupal.org/project/easy_breadcrumb is pretty choice.
They are implementing token into this module. 

https://www.drupal.org/project/easy_breadcrumb/issues/3088784#comment-15659167
https://www.drupal.org/project/easy_breadcrumb/issues/3467372
