### ISSUE TITLE
add eca - rabbit hole the tag page

### ISSUE THREAD

**Issue by simesy** [frees-au/ce#65]
Add ECA (newest branch) and create a model (use bpmn_io) that returns a 404 on taxonomy term pages.

**Comment by tannguyen04** [comment]
Hi @simesy 
I could not find the way to setup return 404 on taxonomy term pages. 
However, I have setup an other demo ECA with bpmn_io is redirect user to /admin/people or <front> page depends on user roles when user login as https://github.com/frees-au/ce/pull/128
